#!/usr/bin/env bash
# This script gracefully restarts Gunicorn without downtime

# Find the process ID (PID) of the Gunicorn master process
PID=$(pgrep gunicorn)

if [ -z "$PID" ]; then
    echo "Gunicorn is not running. Starting Gunicorn..."
    #  start Gunicorn 
    #  gunicorn --bind 0.0.0.0:5000 module:app
    gunicorn --bind 0.0.0.0:5000 module:app &
    echo "OK"
else
    # Send the HUP signal to Gunicorn to initiate a graceful reload
    kill -HUP "$PID"
    echo "OK"
fi
